# Generated by Django 4.2.3 on 2023-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ion-ios-calendar-outline', 'DATE'), ('ion-ios-location-outline', 'location'), ('ion-ios-person-outline', 'speakers'), ('ion-ios-pricetag-outline', 'tickets')], max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
